// File generated by FlutterFire CLI.
// This file is used to configure Firebase for your Flutter app.
// Replace this with your actual Firebase configuration file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration - you'll need to add this from Firebase console if needed
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGA3hsouhjWlO1wLgKamNXHFezx0yIfRI',
    appId: '1:1076421018451:android:1db468b2c48376379497a6',
    messagingSenderId: '1076421018451',
    projectId: 'discount-hub-13c18',
    authDomain: 'discount-hub-13c18.firebaseapp.com',
    storageBucket: 'discount-hub-13c18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGA3hsouhjWlO1wLgKamNXHFezx0yIfRI',
    appId: '1:1076421018451:android:1db468b2c48376379497a6',
    messagingSenderId: '1076421018451',
    projectId: 'discount-hub-13c18',
    storageBucket: 'discount-hub-13c18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGA3hsouhjWlO1wLgKamNXHFezx0yIfRI',
    appId: '1:1076421018451:android:1db468b2c48376379497a6',
    messagingSenderId: '1076421018451',
    projectId: 'discount-hub-13c18',
    storageBucket: 'discount-hub-13c18.firebasestorage.app',
    iosClientId: '1076421018451-ios-client-id', // You'll need to update this with actual iOS client ID
    iosBundleId: 'com.example.discountApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGA3hsouhjWlO1wLgKamNXHFezx0yIfRI',
    appId: '1:1076421018451:android:1db468b2c48376379497a6',
    messagingSenderId: '1076421018451',
    projectId: 'discount-hub-13c18',
    storageBucket: 'discount-hub-13c18.firebasestorage.app',
    iosClientId: '1076421018451-ios-client-id', // You'll need to update this with actual iOS client ID
    iosBundleId: 'com.example.discountApp',
  );
} 